### ISSUE TITLE
Organizing workflow

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#1]
I create this repo so that it is easier to discuss and plan for future SingaporeJS events. Things that covered will include:
- Meetup logistics planning - date, venue, food, sponsor, etc.
- Speakers lineup - have a list of candidate speakers to pick up for future meetups.
- Special events planning - NodeSchool, NodeBots, DevFest, etc.
- Community outreach - there are many meetup groups that approach us and ask for collaborations etc.
- General discussion - how we should run events, how to engage the audience, etc.

This repo is public and anyone is free to contribute. For now @timoxley and I will continue in charge of running the actual events, but we'd like to be more open and get more people involved in the planning process. Hopefully through this we can also find more people to join the core organizer team.

Do give us suggestions on things that we can discuss here. cc @notthetup @sayanee @weilu.

**Comment by sayanee** [comment]
really appreciate this @soareschen :star2: 

thanks for wanting to make awesome talk.js sessions!
