### ISSUE TITLE
WebAudio Hack Day

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#10]
@notthetup suggest we do a [WebAudio Hack Day](http://janmonschke.com/blog/2014/10/03/web-audio-hackday-2014.html) after the NodeSchool event during DevFest (#7). So let's manage the planning here. Will probably also include WebGL as well.

Thomas want us to [submit the application](https://jsconfasia.wufoo.com/forms/devfestasia-2015-list-my-event/) first so that he can plan for DevFest. @notthetup can you take charge to draft the form and submit first?
- [ ] Number of attendees
- [ ] Ticket pricing
- [ ] Sponsorship Amount
- [ ] Date
- [ ] Venue

**Comment by tjiahen** [comment]
Yup,  I can help up with the webgl part. what do I need to do?

**Comment by notthetup** [comment]
@wizztjh So the original idea was a WebAudio Hack Day ala http://janmonschke.com/blog/2014/10/03/web-audio-hackday-2014.html

@timoxley suggested adding WebGL as well. 

The benefit is larger interest (more participants) as well as a potential for more sponsors. 

I should be able to get Sonoport to sponsor, but we need at least 2 more Sponsors if we want to make this event completely sponsor supported (DevFest rules). Any ideas?

The schedule in my mind for the event is: 

11.00 am : Begin
12.30pm : Lunch
1.00pm : Talk on WebAudio (one of JSConf speakers hopefully)
1.30pm : Talk on WebGL?
6.00pm : Dinner
8.00pm : Demos
9.00pm : End

Please feel free to recommend adjustments.

**Comment by tjiahen** [comment]
I think @timoxley is referring to [webgl-workshop](https://github.com/stackgl/webgl-workshop) ?

I will try to ask around.

**Comment by tjiahen** [comment]
Have you guys found the venue?

What is the sponsorship amount?

**Comment by notthetup** [comment]
@wizztjh No venue yet. Sponsorship amount would depend on venue I guess. Let me check with Thomas how about venues then we'll have a ballpark figure.

**Comment by tjiahen** [comment]
I am asking IDA labs for venue for next SGVRAR meetup. What is the date of the event? I can ask them to provide venue for this event at the same time. They provide event venue for free. It can accommodate around 40-50 people.

**Comment by notthetup** [comment]
https://jsconfasia.wufoo.com/forms/devfestasia-2015-list-my-event/
