### ISSUE TITLE
Choose a different weekday for talk.js

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#11]
[Quoting](https://www.facebook.com/miccheng/posts/10153586865127229) @miccheng:

> Really guys? The Drupal, Javascript and Haskell groups all decided to hold their meetup on the same night next Tuesday. Really guys? Check on http://WeBuild.SG before booking can?

Second/Third Tuesday of the month is too popular for meetups. Let's vote for a better date for talk.js and keep it fixed for every month. Brainstorm dates please?
- First/Last Thursday of every month?

Taken by other meetups:
- Papers We Love - Last Monday of every month

**Comment by notthetup** [comment]
Hackware is Last Wednesday of every Month.
FEDS is 3rd Monday

**Comment by soareschen** [comment]
Let's try 3rd or 4th Thursday of every month.
