### ISSUE TITLE
Job Board

### ISSUE THREAD

**Issue by timoxley** [SingaporeJS/organizers#12]
Thinking about setting up a SingaporeJS job board.

Simplest thing that will work would be a new `github.com/SingaporeJS/jobs` repo and job postings are new issues.

Would like to charge for postings, and have that money go into a kitty for future SingaporeJS events, but perhaps that's phase two after we have at least some job postings.

Ideally we would specify some minimum requirements for job posters, such as transparency about salary/benefits.

Any thoughts?

**Comment by quannt** [comment]
:+1: Good idea. Here's something similar that other groups are using https://github.com/ruby-vietnam/job_board

**Comment by tjiahen** [comment]
Or something like http://ruby.sg/companies
