### ISSUE TITLE
ITE web development curriculum feedback

### ISSUE THREAD

**Issue by sebdeckers** [SingaporeJS/organizers#13]
Anyone in this group who wants to help ITE come up with a relevant course for web development? Could help lots of students for many years to come. Only takes one afternoon of sitting in a meeting. Did it before and was pretty rewarding. Can't make it this time due to other obligations.

> Dear Mr Deckers, 
> 
> ITE is exploring a new course in web development to support social media, CMS/ web portal and e-commerce. 
> 
> I will like to invite you to attend a focus group discussion to establish the job scope and duties and tasks for this new course.  
> 
> Details are as follows:  
> 
> Date:                 Tuesday 8 Sep 2015
> Time:                 1430 hrs 
> Venue:         Executive Salon 3, Level 7, Block A 
>                        ITE Headquarters 
>                        2 Ang Mo Kio Drive 
>                        Singapore 567720 
> 
> Your company's participation in this discussion is important as it will help ITE to ensure relevancy and adequacy in the training for the web and social media sector. 
> 
> I will appreciate if you can attend the meeting or pls appoint suitable representatives (experienced Technical personnel in web development) from your company for this meeting. 
> 
> Name of Nominee : 
> Occupational Title: 
> Email and Tel#: 
> Number of Years on the Job: 
> Name of Organisation/Company: 
> 
> I will then liaise directly with him/her. If you need further information, pls do not hesitate to contact me.  Thank you for your consideration, and looking forward to your favourable reply.
> Jill Soh 
> Curriculum Development Specialist / Electronics & Info-Comm 
> Curriculum & Educational Development Division, Institute of Technical Education, 2 Ang Mo Kio Drive, Singapore 567720  
> Tel: +65 6590 2325 | Fax: +65 6590 2347 | Website: www.ite.edu.sg

**Comment by notthetup** [comment]
This is great. I wonder whom within the community we can ask to help here. 

As a community I think we should help in such initiatives, it will only help to strengthen the community as more students come armed with the right skills to contribute to the community.

**Comment by notthetup** [comment]
@coffeesam Would you be interested in this ^ ?

**Comment by sebdeckers** [comment]
Ended up unable to attend. Have failed the future students of ITE's course. :sob: Deity have mercy...

**Comment by notthetup** [comment]
:(
