### ISSUE TITLE
talk.js DevFest Special Edition

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#15]
http://www.meetup.com/Singapore-JS/events/226393928/

We will have a special edition of talk.js for DevFest.Asia on Tuesday November 17th.
## Speakers
- Simon Swain
- Joshua Koo 
## TODO
- [x] Venue
- [x] Sponsorship

**Comment by notthetup** [comment]
Sounds good (y). It'll be like RejectJS. :)
