### ISSUE TITLE
talk.js October Edition

### ISSUE THREAD

**Issue by notthetup** [SingaporeJS/organizers#16]
- [x] Date: Wednesday, October 21, 2015
- [x]  Venue : PayPal
- [x] Food sponsor: PayPal
- [x] Speakers
- [x] Announce on meetup.com
- [x] Announce on Facebook (SingaporeJS, FEDS)
- [ ] Security guest list
- [x] Reminder on day of talk before noon.

Speakers : 
- [x] Yap Hong Kheng - Fetch API
- [x] Chen Hui Jing - Using Responsive Images Now 
- [x] Sebastiaan Deckers -  Software license auditing with SPDX and package.json
- [ ] ?? - BitTitan?

**Comment by sebdeckers** [comment]
@notthetup @soareschen May I please give an ill-prepared talk about software license auditing and how SPDX and package.json will save the world?

**Comment by notthetup** [comment]
:+1:
