### ISSUE TITLE
talk.js Douglas Crockford Special Edition

### ISSUE THREAD

**Issue by notthetup** [SingaporeJS/organizers#17]
http://www.meetup.com/Singapore-JS/events/226070428/
- [x] Date: Wednesday, November 4, 2015
- [x]  Venue : PayPal
- [x] Food sponsor: PayPal
- [x] Speakers
- [x] Announce on meetup.com
- [ ] Announce on Facebook (SingaporeJS, FEDS)
- [ ] Security guest list
- [ ] Reminder on day of talk before noon.

Speakers : 
- [x] Douglas Crockford

**Comment by quannt** [comment]
wow :+1:
