### ISSUE TITLE
Douglas Crockford fireside chat questions

### ISSUE THREAD

**Issue by sayanee** [SingaporeJS/organizers#18]
Related to #17  and [meetup](http://www.meetup.com/Singapore-JS/events/226070428/)

Format of fireside chat :alarm_clock: 30 minutes:
- :alarm_clock: 15 minutes: curated questions
- :alarm_clock: 15 minutes live audience questions

The preliminary ideas on the themes of the fireside chat are:
- Upgrading the Web ([related to his talk](http://www.meetup.com/Singapore-JS/events/226070428/))
- Perspective on how web development has changed since the time he started

@soareschen @cbas @huijing @timoxley @cheeaun @alyssaq @zz85 @notthetup @serrynaimo @weilu @laurenceputra @hongkheng (please feel free to tag more :heart_eyes:)
- What would you like to ask him? 
- What other themes should the fireside chat focus on?

_Note: I will continuously edit this as the discussion progresses_

**Comment by sebdeckers** [comment]
#### JavaScript in the Browser
- Is there room on the web for other languages?
- What benefits are there to the JS monopoly?
- Are transpilation-friendly features in ECMAScript leading up to a Cambrian explosion of second-class web languages?

#### JavaScript in Other Environments
- How much of JavaScript's renaissance is attributable to Node.js and NPM (or vice-versa)?
- Which other platforms will be dominated by JavaScript in the future? IOT, mobile?

#### Language Design
- With so many stakeholders, is the language becoming multi-paradigm? E.g. `class` vs `prototype`, high-level (`await`/`async`, etc) vs low-level (SIMD, Atomics, etc)
- What are the understated language features that could change how we write JavaScript in the future? For example how ES5's Array iterators led to Underscore/Lodash and virtually eliminated traditional `for`/`while` loops.

**Comment by soareschen** [comment]
A bit of cheating: Douglas have gave this talk before and you can pre-listen to the talk at YouTube: https://www.youtube.com/watch?v=YRo2GStE3Qg

**Comment by sayanee** [comment]
@cbas - Excellent questions! These should be enough for both curated and fill-in questions.

@soareschen :satisfied: ok i have some homework to do this weekend to prep! Thanks!

**Comment by notthetup** [comment]
@sayanee As I mentioned earlier, https://devchat.tv/js-jabber/168-jsj-the-future-of-javascript-with-jafar-husain is a great interview about the future of JS which might be great background knowledge.

**Comment by notthetup** [comment]
https://www.youtube.com/watch?v=FHRXPlq9XNw

**Comment by soareschen** [comment]
I have some questions for Douglas' Seif project proposal.
- I can relate to HTML not being the perfect UI for the web, but why Qt instead?
- If we have the chance to reinvent the web, why keep JavaScript as the only language for the web?

**Comment by notthetup** [comment]
Hehehehe.. 
1. I wondered about that too.. Qt uses XML?
2. I guess cos he's a big JS fan.. :P

**Comment by alyssaq** [comment]
Qt QML looks like JSON that can be integrated with javascript. (http://doc.qt.io/qt-5/qtqml-syntax-basics.html). Kinda neat

**Comment by sayanee** [comment]
Thanks @soareschen and @notthetup for the inputs. Seems like the general themes that I will start off in the fireside chat will be:
1. Possibility of other languages for the web 
2. JavaScript beyond web for hardware, networking, sysadmin, etc
3. JavaScript language design

@soareschen Seif project will be a great first audience question to get the ball rolling!

**Comment by serrynaimo** [comment]
As a pre-caution for tonight :) https://twitter.com/jashkenas/status/611277674191978496

**Comment by zz85** [comment]
Questions for Douglas
1. you don't seem like a bad person in real life. why do you like hurting people feelings?
2. with many other alternatives today to jslint (eg. jshint, eslint, jscs etc), do you feel that less feelings are hurt today?

**Comment by sebdeckers** [comment]
Seif questions:
- crypto > dns = namecoin???
- did xmpp fail because it used dns and xml instead of json?
- spam was killed by IM apps (wechat, fb msg) -- would that be a suitable approach for Seif to gain adoption as a protocol instead of the web?

**Comment by sayanee** [comment]
Thanks everyone for your inputs! Really enjoyed the audience questions yesterday  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by cheeaun** [comment]
:+1:
