### ISSUE TITLE
NodeSchool DevFest.Asia

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#19]
http://www.meetup.com/Singapore-JS/events/226393698/
- Date: Sunday 15 November
- Time: 10am - 5pm
- Venue: Microsoft Singapore

TODO:
- [x] Create meetup page
- [x] Find mentors
- [ ] Arrange food & beverages
- [ ] Select workshops to cover
- [ ] Save materials in thumbdrives
# Workshops to Cover

Please suggest the workshops that we should cover, choosing from http://nodeschool.io/. Here is my short list:
## Beginners
- [JavaScripting](https://github.com/sethvincent/javascripting)
- [Functional JavaScript](https://github.com/timoxley/functional-javascript-workshop)
- [Learn You Node](https://github.com/workshopper/learnyounode)
## Intermediate
- [Scope Chains And Closures](https://github.com/jesstelford/scope-chains-closures)
- [Planet Proto](https://github.com/sporto/planetproto)
## Advanced
- [Learn Generators](https://github.com/isRuslan/learn-generators)
## Platform Specific
- [Web Audio School](https://github.com/mmckegg/web-audio-school)
- [Learn You React](https://github.com/tako-black/learnyoureact)
# Mentors

Please help find mentors to help up during the workshop!
## Confirmed
- [x] @soareschen
- [x] @timoxley
- [x] @notthetup 
- [x] @sneakertack
- [x] @yangzai
- [x] @cbas
- [x] @zz85
- [x] @mdda
## Unconfirmed
- [ ] @alyssaq
- [ ] @sayanee
## Not Going
- @weilu
- @cliener

**Comment by soareschen** [comment]
Draft meetup page for NodeSchool: http://www.meetup.com/Singapore-JS/events/226393698/

**Comment by sebdeckers** [comment]
Been teaching a few Nodeschool workshops to a group of students. One thing to look out for is that the workshops don't seem to print the solution code. Seems like a bug but didn't yet investigate which module is at fault.

**Comment by timoxley** [comment]
cc @mdda

**Comment by soareschen** [comment]
Tentative schedule for the day:
- 10:00-10:30 - Welcome and introduction
- 10:30 - 13:00 - Workshop session 1
  - Functional Javascript
  - Scope Chains And Closures
  - Web Audio School
- 13:00 - 14:00 - Lunch break
- 14:00 - 16:30 - Workshop session 2
  - Learn You Node
  - Planet Proto 
  - Learn You React 

Things to note:
- First time participants to NodeSchool are encouraged to work on Functional Javascript or Learn You Node.
- Special tracks Web Audio School and Learn You React are for intermediate learners with basic knowledge in JavaScript.
- Participants who have joined NodeSchool before can work on Scope Chains And Closures and Planet Proto. I don't expect many but will put this up just in case.
- We will have two more on-demand workshops for participants who do not fit in to the existing workshops:
  - JavaScripting for absolute beginners.
  - Learn Generators for advanced learners.

**Comment by soareschen** [comment]
Instructions for mentors:
- Complete at least 1~2 workshops to get yourself familiar with NodeSchool. I would recommend trying Functional JavaScript and Learn You Node.
- We will have an informal mentorship session at HackerspaceSG this Saturday. If you are free that day, [register on Meetup](http://www.meetup.com/Singapore-JS/events/226722668/) and come join us. Otherwise just show up on Sunday to help up.
- Help make sure the venue is all clean after the event.
- Read NodeSchool wiki for guidelines on [becoming a mentor](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)
- Please register yourself at [DevFest.Asia](https://www.eventnook.com/event/devfestasia2015/home) with the discount code NSMENTORS.

**Comment by sneakertack** [comment]
Can't make it for tomorrow (Sat), will be there on Sun. Will spend time to review the workshops again tomorrow.
