### ISSUE TITLE
talk.js August Meetup

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#2]
Tasks:
- [x] Date: Tuesday 18th August
- [x] Venue: PayPal
- [x] Food sponsor: PayPal
- [x] Speakers
- [x] Announce at meetup.com
- [x] Announce at Facebook
- [x] Security guest list
- [x] Reminder on day of talk before noon.

Speakers:
- [x] Jacky Boen - The Imitation Game: Redux - 20 mins
- [x] Zell Liew - Gulp.js (first time speaker) - 10 mins
- [x] João Bentes (first time speaker) - 5 mins

http://www.meetup.com/Singapore-JS/events/224276007/

**Comment by notthetup** [comment]
:+1: Looks great!

**Comment by sayanee** [comment]
:+1: yep confirm it :smile:

**Comment by soareschen** [comment]
Microsoft can't host it at that day. Shall we host it at PayPal?

**Comment by notthetup** [comment]
OK

**Comment by sayanee** [comment]
:+1: yeps PayPal

**Comment by soareschen** [comment]
Have confirmed booking with PayPal. Next will inform and confirm the speakers. Can anyone put here the names of the suggested speakers for lightning talk again?

**Comment by sayanee** [comment]
possible lightning talk form the nodebots organisers on future nodebots - by pasindu and nathania

**Comment by soareschen** [comment]
Meetup ended successfully. Thanks everyone for the great work!
