### ISSUE TITLE
Front End TL;DR Venues

### ISSUE THREAD

**Issue by shawnlimws** [SingaporeJS/organizers#23]
@caalberts, we can compile the possible venues here, and maybe we can approach Sonoport for the coming one?  

Just of the top of my head, I put in a few places. I also got some places from data.webuild.sg, but not sure if Front End has already been there before or if there are suitable :) @cbas 
# Possible Venues
1. Sonoport - @hongkheng
2. Redmart - 
3. Tech In Asia -
4. Thoughtworks -
5. Neo -
6. Skyscanner -
7. TradeGecko -

**Comment by caalberts** [comment]
# Possible Venues
1. Sonoport - @hongkheng
2. Redmart -
3. Tech In Asia -
4. Thoughtworks -
5. Neo -
6. Skyscanner -
7. TradeGecko -
8. IDA Hive -

**Comment by sebdeckers** [comment]
- Smove

**Comment by shawnlimws** [comment]
hey @caalberts! have the people at IDA gotten back to you? If not we might have to try other venues already.

**Comment by caalberts** [comment]
@shawnlimws no news yet. I've also contacted MRM// McCann (agency)

I think we should try all possible venues. If we have more than one we can queue them for future meetups.

**Comment by shawnlimws** [comment]
oh oh! sounds good too.. let me contact the sonoport person then :)

**Comment by sebdeckers** [comment]
- Honestbee (they're hosting _everything_ lately :+1: )

**Comment by shawnlimws** [comment]
hey @cbas! do you know who I can contact from honestbee?

**Comment by sebdeckers** [comment]
@shawnlimws I'd try attending one of the many events at their office. Or contacting others who organise events that take place there and ask for an intro.

**Comment by notthetup** [comment]
@shawnlimws If you can't get through, I can try to ask Issac who's one of the co-founders I think.

**Comment by caalberts** [comment]
@shawnlimws YJ knows the honestbee person who organised one of the data meetup he attended. Asking him to intro.

**Comment by caalberts** [comment]
@shawnlimws got in touch with the Honestbee person. Cc you in the email

**Comment by caalberts** [comment]
@notthetup got in contact with Isaac too. thanks :+1:

**Comment by shawnlimws** [comment]
@caalberts I contacted sonoport already through hongkheng.. so waiting for an update :)

**Comment by caalberts** [comment]
- glints - another possibility
