### ISSUE TITLE
Front End TL;DR List of Suggested Topics

### ISSUE THREAD

**Issue by caalberts** [SingaporeJS/organizers#24]
@cbas @shawnlimws - List of topics for suggestions. Some from newsletters, some from word of mouth.
- [ ] [Preact - fast React alternative](http://developit.github.io/preact/)
- [ ] [Offline page with service workers](http://deanhume.com/Home/BlogPost/create-a-really--really-simple-offline-page-using-service-workers/10135)
- [ ] [Codepen console](http://blog.codepen.io/2016/01/27/new-feature-javascript-console/)
- [ ] [Origami.js - HTML5 Canvas for Humans | 人間のためのキャンバス](https://github.com/raphamorim/origami.js)
- [ ] [Cytoscape.js - graph theory](http://js.cytoscape.org/)
- [ ] [Nodegram - simple Instagram API](https://github.com/zzarcon/nodegram)
- [ ] [Nightmare - A high-level browser automation library](http://www.nightmarejs.org/)

**Comment by shawnlimws** [comment]
- [ ] [Aurelia framework](http://aurelia.io/)

**Comment by caalberts** [comment]
- [ ] [nightwatch js - browser automated test](http://nightwatchjs.org/)
- [ ] [samsarajs](http://samsarajs.org/)
- [ ] [ES2015 proxies](https://developers.google.com/web/updates/2016/02/es2015-proxies)

**Comment by joeytwiddle** [comment]
[Inferno](https://github.com/trueadm/inferno) is another fast React alternative with mostly the same API. (For comparison.)
