### ISSUE TITLE
talk.js - May 2016

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#29]
#### Details
- [x] Date: May 19, 2016
- [x] Hosts: @ongmin and @jsstrn
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal
#### Speakers
- [x] How well do you know your Functions? - Tim Oxley 
- [x] Taxi Router - Chee aun
- [x] es6+angular development - Krishna Murali
- [x] :no_entry_sign: :fearful:  - Chris Lienert 
- If you would like to speak, please ping!

**Note to speakers:** Add a comment to share links to your slides.
#### Organizers' to-dos
- [x] Announce on SingaporeJS Meetup Page
- [x] Announce on SingaporeJS Gitter
- [x] Announce on SingaporeJS Facebook Group
- [x] Send out a reminder one day before event to all channels listed above

\* checked boxes indicate confirmed/done

**Comment by ongmin** [comment]
Few notes:
- Less technical talks this round, with 1 quiz, 1 width topic (fear) and 1 sharing of pet project.
- Audience seemed engaged in the interactive talks.
- Less people came forward to suggest talks this month, 1 day-1 withdrawal.

Closing issue...
