### ISSUE TITLE
Guidelines for first time speakers

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#3]
We need some policies for first time speakers to better control the quality of the talks. Here are some of my thoughts:
- First time speakers include people with first time experience speaker, and experienced speakers speaking for the first time in talk.js.
- For first time experience speakers, the time limit should be 5-10 minutes.
- Experienced speakers are given the usual time limit of 20 mins. There should be online video recording of their previous presentations or be recommended by regular members.
- For both kind of first time speakers, we should ask for their draft presentation slides 3 days before the meetup.
- Any issue with the presentation content should be raised up in the GitHub issue for that meetup.

Are these policies fair enough or should we try to be more flexible?

**Comment by notthetup** [comment]
I like having time limits. But 5-10mins might surprise many people.

Also a lot of new speakers can't estimate how much time their talk will take. A timer would be helpful. http://sayan.ee/timer/

**Comment by sayanee** [comment]
First time speaker should be lightning talks for 5 minutes and demo only. No pitches. We can ask if they need pre-talk feedback and we can give them support for this.

**Comment by soareschen** [comment]
@notthetup: what do you mean by surprise people?

I think for the next meetup can try out the format: 1 x 20 mins and 2~3 x 5~10 mins talks. Agree with @sayanee on keeping fresh beginners at 5 minutes. Special guests and exceptions can be made on the specific meetup thread.

**Comment by notthetup** [comment]
Surprise in the sense, they might think it's too little. They might be used to longer slots. Just something to keep in mind.

**Comment by timoxley** [comment]
Yeah we really need to enforce time limits. I always forget to start a timer.

**Comment by timoxley** [comment]
Also, these shouldn't be policies per se, but more guidelines.
