### ISSUE TITLE
talk.js - June 2016

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/organizers#30]
#### Details
- [x] Date: June 30, 2016
- [x] Hosts: @ongmin (@jsstrn away)
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal
#### Speakers
- [x] GPU design with Javascript - Shipeng Xu
- [x] DNA Genealogy - Andreas West 
- [x] Progressive Web App - Thye Yeow Bok
- If you would like to speak (this or next months), please ping!

**Note to speakers:** Add a comment to share links to your slides.
#### Organizers' to-dos
- [x] Announce on SingaporeJS Meetup Page
- [x] Announce on SingaporeJS Gitter
- [x] Announce on SingaporeJS Facebook Group
- [ ] Send out a reminder one day before event to all channels listed above

\* checked boxes indicate confirmed/done

**Comment by ongmin** [comment]
Link to Shipeng's talk (GPU design with Javascript)'s repo: https://github.com/billhsu/renderer.js

**Comment by jsstrn** [comment]
I'll be away from 22 June to 30 July.

**Comment by sebdeckers** [comment]
Guess this can be closed now? Is the `(Active)` in the title meant to be a label? GH Issues supports labels natively so no need to overload the issue title. And one could probably just use `Open`/`Closed` status. $0.02
