### ISSUE TITLE
talk.js - July 2016

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#31]
> **Instructions**: Copy and paste the text below, add a comment and fill up the respective fields.

**Title of your talk**: _insert catchy title here_
**Talk description**: _tell us what you'd like to talk about_
**Presenters**: _include your GitHub handles where possible_
**Duration requested**: _lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)_
**Deck URL** (if any): _you can add this part in later_

**Comment by giftofjehovah** [comment]
**Title of your talk**: Telegram Bot
**Talk description**: sharing our experience building a telegram bot in AngelHack 2016, advantages and potential of a bot, future plans.
**Presenters**: @giftofjehovah, @silverframe, @finalight, @cxchua
**Duration**: regular (15 to 20 min) _\- edit by min (default (10mins + 5mins Q&A)_
**Deck URL (if any)**: will add in later

**Comment by gabrielle-ong** [comment]
**Title of your talk:** More than a donation...
**Talk description:** Sharing our hack from our FB Hackathon
**Presenters:** @jolozy, @chelimin, @gabrielle-ong, @yangshun
**Duration:** lightning (5 min) - _ok!_
**Deck URL:** later

**Comment by gabrielle-ong** [comment]
@ongmin @jsstrn when is the July meetup?

**Comment by ongmin** [comment]
Heyhey, should be 3rd or 4th week of July. We haven't fixed the dates but
will start to do it in advance soon.

**Comment by jsstrn** [comment]
Thanks for organizing this @ongmin!

**Comment by sebdeckers** [comment]
Can I please propose one more short-ish talk?

## Title of your talk

The Promise of HTTP/2 Server Push

## Talk description

Optimising asset delivery over HTTP/1.1 necessitated hacky "best practices" that are obsoleted by the design of HTTP/2. Features like stream multiplexing and header compression are easy to deploy, free wins. But HTTP/2 Push requires a rethink of some old habits. No more sprites, no more concatenating, no more icon fonts. Let's take a look at HTTP/2 Push and see if it delivers on its promises (pun intended). The holy grail is to serve an entire app, thousands of files, using a single request.

## Presenter

Sebastiaan Deckers :octocat: [github:cbas](https://github.com/cbas) or 🐺  [gitlab:sebdeckers](https://gitlab.com/sebdeckers)

## Duration

regular (15 to 20 min) _\- ok!_

## Deck URL

Talk is iteration on a presentation I gave at SF Node in July '16 https://gitlab.com/sebdeckers/talk-sfnode-http2
Demo https://gitlab.com/sebdeckers/push-demo
Project https://www.npmjs.com/package/http2server

**Comment by ongmin** [comment]
Awesome! :D Could be fun if you shared a little about the good parts observed from the meetups you go to elsewhere too @cbas !

**Comment by ongmin** [comment]
Meetup set on 27th July (Wed), hope that works for everyone!
Here: http://www.meetup.com/Singapore-JS/events/232635616/

**Comment by ongmin** [comment]
http://carparks-sg.herokuapp.com/ - David Tan @davified

**Comment by davified** [comment]
**Title of your talk**: Visualising real-time carpark data with Carparks-SG (or, How to have fun with LTA Data Mall)
**Talk description**: I'll discuss and walk through my code for Carparks-SG, which is an app built using Node and Express (http://carparks-sg.herokuapp.com/)
**Presenter**: @davified
**Duration**: 10 mins + 5 mins Q&A _\- ok!_
**Deck URL**: (can i send it to you on Tues night?)

**Comment by gabrielle-ong** [comment]
Hey @ongmin, can @giftofjehovah's group and my group swop slots? We prefer
each other's slots:P

**Comment by ongmin** [comment]
@gabrielle-ong @giftofjehovah hello! done. :)

**Comment by davified** [comment]
hey @ongmin , sorry for the delay. here are my slides! http://bit.ly/2ard8f0
