### ISSUE TITLE
talk.js - upcoming dates

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/organizers#34]
- 25 Aug (Thurs)
- 29 Sep (Thurs)
- 27 Oct (Thurs)
- 24 Nov (Thurs) - DevFest Special

**Comment by timoxley** [comment]
@ongmin are these confirmed?

**Comment by ongmin** [comment]
@timoxley yup, we've booked the hall with paypal. :) the events were also created on meetup, under drafts.
