### ISSUE TITLE
talk.js - November 2016 - DevFest Special

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/organizers#35]
### Details
- [x] Event URL: [talk.js](https://www.meetup.com/Singapore-JS/events/232635707/)
- [x] Date: November 24, 2016 - Thursday
- [x] Hosts: @jsstrn @cbas 
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal

### Speakers
- [x] Paws on Progressive Web Apps by @hemanth 
- [x] Serverless AWS JavaScript Apps by @kaihendry 
- [x] JavaScript in the Enterprise by Ashwin Vombatkere
- [x] How (Not) to Build an Augmented Reality App in 3 Weeks by @ZhangYiJiang 
- [ ] You?

_Want to speak at this month's talk? Leave a comment below with the following details:_

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)
> **Deck URL (if any)**: you can add this part in later

### Note to speakers
- Talks should not be a company pitch or about job opportunities; make such announcements during the open mic segment
- If you require wifi access for your talk, approach the host for wifi credentials **before** the start of your talk
- Register yourself on our event's page (see event URL above) and bring along a photo ID for building security verification

### Organizers' to-dos
- [x] Create event on SingaporeJS Meetup Page
- [x] Submit attendee list to venue host
- [x] Create slide deck for event
- [ ] Announce on social media (Facebook, Twitter, Gitter, etc.)

\* _checked boxes indicate confirmed/done_

**Comment by ongmin** [comment]
+ Hemanth (https://github.com/hemanth)

**Comment by jsstrn** [comment]
Want to speak at this month's talk? Leave a comment below with the following details:

> Title of your talk: insert catchy title here
Talk description: tell us what you'd like to talk about
Presenters: include your GitHub handles where possible
Duration requested: lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)
Deck URL (if any): you can add this part in later

**Comment by jsstrn** [comment]
Hi @hemanth, would you be able to provide details of your proposed talk? Fill up these details:

> Title of your talk: insert catchy title here
> 
> Talk description: tell us what you'd like to talk about
> 
> Presenters: include your GitHub handles where possible
> 
> Duration requested: lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)
> 
> Deck URL (if any): you can add this part in later

**Comment by hemanth** [comment]
Sure. 

Title of your talk: Paws on PWA.

Talk description: Introduction to progressivewebapps, this talk shall walk you through the different ingredients that make a PWA. (Serviceworkers, ATHS, BackgroundSync, PushNotification being the major areas that will be covered)

Presenters: @hemanth

Duration requested: long (15min + 5mins Q&A)

**Comment by jsstrn** [comment]
Looking forward to the talk, @hemanth.

**Comment by kaihendry** [comment]
Title of your talk: Serverless AWS JS apps
Talk description: Sharing experiences of creating a serverless Web app for company employees
Presenter: @kaihendry
Presenter's bio: #juniordevforlife
Duration requested: default
Deck URL: http://talks.webconverger.com/2016-11-24/

**Comment by jsstrn** [comment]
Hi @kaihendry, looking forward to your talk.

**Comment by jsstrn** [comment]
Don't forget to register for the event on [Meetup.com](https://www.meetup.com/Singapore-JS/events/232635707/).

**Comment by ZhangYiJiang** [comment]
Apologies if this is too late for inclusion in this month's meetup - if it is, please move this to next month's instead. 

Title of your talk: How (not) to Build an Augmented Reality App in 3 Weeks 
Talk description: Lessons learnt from building an augmented reality mobile web application in three weeks for CS3216 Software Product Engineering on Digital Platforms 
Presenter: @ZhangYiJiang 
Presenter's bio: A second year Computer Science student at National University of Singapore doing freelance full-stack web development with a penchant for small technicolored horses and speaking about himself in third person. Personal website - https://meebleforp.com/ 
Duration requested: Default (although may not use up the full 10 min)

**Comment by jsstrn** [comment]
Looking forward to your talk @ZhangYiJiang! 🎉
