### ISSUE TITLE
talk.js - September 2016

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#36]
### Details
- [x] Event URL: [talk.js](https://www.meetup.com/Singapore-JS/events/232635720/)
- [x] Date: September 29, 2016 - Thursday
- [x] Hosts: @jsstrn
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal
### Organizers' to-dos
- [x] Announce on SingaporeJS Meetup Page
- [x] Announce on SingaporeJS Gitter
- [ ] Announce on SingaporeJS Facebook Group
### Speakers
- [x] Debugging JavaScript without `console.log` by Sher Minn Chong @piratefsh 
- [x] Building TicTacToe with React Native and SocketIO by Zhenjie Lee @finalight
- [x] JavaScript on the JVM by Stephan H. Wissel @Stwissel 

Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenters**: include your GitHub handles where possible
> **Duration requested**: lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)
> **Deck URL (if any)**: you can add this part in later

\* _checked boxes indicate confirmed/done_

**Comment by piratefsh** [comment]
hey hey! i'd like to give a talk.

Title of your talk: Debugging JavaScript, without console.log (!!!)

Talk description: Let's talk about debugging JavaScript. Most of us start out learning how to debug by logging stuff to the console. But sometimes, that doesn't tell us enough. Was my DOM element updated at all? What series of events led to that error? What if things are crashing in library code that you don't have access to? 

In this talk, we'll go through the basics of the Chrome devtools debugger, inspecting variables during runtime, tracing stack calls, as well as debugging library code. We'll also run through a couple of real life bugs with the debugger and talk about how you can start getting comfortable with using it.

Presenters: Sher Minn Chong @piratefsh
Duration requested: default 
Deck URL (if any): n/a yet

**Comment by jsstrn** [comment]
@piratefsh awesome!

**Comment by jsstrn** [comment]
Hi @taras can I confirm that you'll be giving this talk this month?

**Comment by taras** [comment]
@jsstrn I'm not sure if I'll be in Asia at that time. I'm sorry I can't commit for this one.

**Comment by Stwissel** [comment]
I'd like to present:
**JavaScript on the JVM**
With the Java8 JVM the build in JavaScript engine has been upgraded from "Rhino" to "Nashorn". Together with the [Vert.x](http://vertx.ion) project that enables JavaScript execution without the V8 or NodeJS. It offers "Java" shops to tiptoe into JavaScript applications.
I will provide an introduction, code samples and comparison to nodeJS

... could be next month too

**Comment by jsstrn** [comment]
@Stwissel I've updated this month's talk.js agenda with your talk. See you this Thursday then.

**Comment by Stwissel** [comment]
Excellent. See you Thursday!

**Comment by jsstrn** [comment]
Thanks @piratefsh @finalight @Stwissel for your interesting talks yesterday.. it was a pleasure learning from all of you.
