### ISSUE TITLE
talk.js - October 2016

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#37]
### Details
- [x] Event URL: [talk.js](https://www.meetup.com/Singapore-JS/events/232635721/)
- [x] Date: October 27, 2016 - Thursday
- [x] Hosts: @jsstrn
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal
### Speakers
- [x] Babel plugins: Writing code that writes code by @cbas - 10min
- [x] TypeScript 101 by @andyshuhsin - 10min
- [x] Introduction to Vue.js by @phanan - 15min
- [x] Modern JavaScript with React, Redux, GraphQL, Docker by iHealth - 15min
- [ ] You?

Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenters**: include your GitHub handles where possible
> **Duration requested**: lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)
> **Deck URL (if any)**: you can add this part in later
### Organizers' to-dos
- [x] Create event on SingaporeJS Meetup Page
- [x] Announce on SingaporeJS Gitter
- [x] Announce on Twitter
- [x] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by sebdeckers** [comment]
For your consideration...

**Title of your talk:** Babel Plugins: Writing code that writes code
**Talk description:** Taking a closer look at what else Babel can do for us besides ESnext support. Let's use custom Babel transformations, aka codemods, in the build pipeline.
**Presenter:** gitlab:sebdeckers
**Duration requested:** default (10min + 5mins Q&A)
**Deck URL:** will add a repo of content, if any, once I prep for the talk

**Edit**:
Slides are at https://gitpitch.com/sebdeckers/talk-singaporejs-babel?grs=gitlab
Source is at https://gitlab.com/sebdeckers/talk-singaporejs-babel

**Edit**:
Video is at https://engineers.sg/video/babel-plugins-writing-code-that-writes-code-singaporejs--1233

**Comment by jsstrn** [comment]
@cbas would love to have you talk at this month's talk.js 👾

**Comment by blaesus** [comment]
This will be my first time at talk.js and I'm not based in Singapore (I'll be travelling). Is that OK? Anyways, here's my proposal.

Title of your talk: TypeScript 101
Talk description: benefits of TypeScript (over vanilla JavaScript) — type safety, code completion, documentation in code, et al.
Presenters: @andyshuhsin
Duration requested: long (15min + 5mins Q&A); 10min+5min is also doable.
Deck URL (if any): None yet; need some preparation.

**Comment by kevingzhang** [comment]
Hi there,

I am Kevin Zhang, CTO of iHealth labs US. In Aug talk.js I had a 5 minutes open mic talking about iHealth Singapore.  This month, there are 8 software engineers coming to Singapore from Silicon Valley with me. We are setting up iHealth(Singapore) Pte Ltd. Our US Engineers plan to have a technical talk about modern business app stack we are using in Silicon Valley. 
- React, Redux
- GraphQL, Apollo
- React Native
- Docker

We hope to share the experiences and pitfall we gained these months. I hope to we can have the chance. 

Please let me know if we can make it. I will arrive Singapore this Friday Oct 14. 
thanks

**Comment by jsstrn** [comment]
Hi @andyshuhsin, of course that's okay. We love it when people from other parts of the world come and give a talk. Looking forward to your talk on TypeScript.

**Comment by jsstrn** [comment]
Hi @kevingzhang, if you (or your team) would like to give a talk could you fill up the details below? Thank you.

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenters**: include your GitHub handles where possible
> **Duration requested**: lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)
> **Deck URL (if any)**: you can add this part in later

**Comment by phanan** [comment]
For your consideration:

Title of your talk: A quick introduction to Vue.js
Talk description: Introduction to Vue.js, the rising progressive JavaScript framework – what it is, how it's different, and what makes it a 30K-stars-and-counting project on GitHub. 
Presenters: @phanan (Vue's core team member)
Duration requested: default (10min + 5mins Q&A)
Deck URL (if any): N/A

**Comment by kevingzhang** [comment]
Hi @jsstrn  sorry for my late reply, was on the one of the longest flight from SFO to SIN.
Yes, sure, our team (not only me) would like to give a talk. 

Title of the talk:" Modern JS Tech Stack on React Redux GraphQL, Docker and more"
Description: "In this talk, we are going to show our tech stack on iHealth (Singapore). All speakers are coming from iHealth US Silicon Valley office. We will go through the latest coolest technologies in Silicon Valley, such as React Redux GraphQL(Apollo), ReactNative, Realm, Docker and more. We can build modern rich UX webapp/mobile app faster. We would also share our ideas on global team collaboration. This is actually how iHealth works globally. "
Presenters: "iHealth US Silicon Valley team" (4~5 team member may talk on the stage)
Duration: Since we have so many people talk on different layer of the stack, I propose to have 15 min + Q&A
Deck URL: N/A yet.

**Comment by jsstrn** [comment]
Hi @phanan and @kevingzhang, looking forward to your talks next week.

**Comment by kevingzhang** [comment]
Thanks @jsstrn . Do our team members need to go there earlier to prepare something?

**Comment by jsstrn** [comment]
No preparations required on our side. Be there at 7p for pizza and drinks
and chit chat. We start the talks at 7.30p.

**Comment by phanan** [comment]
@jsstrn Can you make my talk a 15' instead? Sorry for the change of plan.

**Comment by sebdeckers** [comment]
@jsstrn Thanks for the excellent event last night. 🙇 

If I might make one suggestion it would be to have a timer facing the speaker. I tend to lose track of time and overrun. Apologies for that last night.

**Comment by jsstrn** [comment]
@cbas glad you enjoyed last month's meet up.. I'll definitely consider your suggestion. Thank you for your feedback.
