### ISSUE TITLE
talk.js - December 2016

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#38]
### Details
- [ ] Event URL on Meetup.com: [talk.js]()
- [x] Date: December 29, 2016 - Thursday
- [x] Hosts: @jsstrn @sebdeckers 
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal

### Speakers
- [ ] How (Not) to Build an Augmented Reality App in 3 Weeks by @ZhangYiJiang
- [ ] You? 😉 

Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: 5min, 10min, 15min
> **Deck URL (if any)**: you can add this part in later

### Organizers' to-dos
- [ ] Create event on SingaporeJS Meetup Page
- [ ] Announce on SingaporeJS Gitter, Twitter, Facebook, etc.
- [ ] Submit attendee list to venue host
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by jsstrn** [comment]
Hi @ZhangYiJiang, would you like to give your proposed talk this month?

**Comment by sebdeckers** [comment]
@jsstrn Was the December event cancelled? Didn't see it on Webuild.

**Comment by jsstrn** [comment]
@sebdeckers yes, there were no speakers for December. Didn't get your memo on wanting to do a end of year special at your place. Thought that was a good idea though.
