### ISSUE TITLE
talk.js - January 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#39]
### Details
- [x] Event URL on Meetup.com: [talk.js](https://www.meetup.com/Singapore-JS/events/236855197/)
- [x] Date: January 26, 2016 - Thursday
- [x] Hosts: @ongmin @jsstrn @sebdeckers 
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal

### Speakers
- [x] Why progressive JPEGs and HTTP/2 are BFFs by Inian
- [x] Protocol Buffers & JSON by Sunny Singh
- [x] PrimeNG - Angular 2 UI component library by Sudheer Jonna

**Fully booked for this month.** Please submit proposed talks to https://github.com/SingaporeJS/organizers/issues/40

Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: 5min, 10min, 15min
> **Deck URL (if any)**: you can add this part in later

### Organizers' to-dos
- [x] Create event on SingaporeJS Meetup Page
- [x] Announce on SingaporeJS Gitter, Twitter, Facebook, etc.
- [x] Submit attendee list to venue host
- [x] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by inian** [comment]
**Title**
Why progressive JPEGs and HTTP/2 are BFFs

**Talk description** 
I will explain what progressive JPEGs are, their benefits and how they are going to be even more awesome when used along with a website with HTTP/2. 

**Presenter** 
Inian Parameshwaran 
http://github.com/inian
https://twitter.com/everConfusedGuy

**Presenter's bio**
Inian Parameshwaran is the founder of Dexecure (https://dexecure.com) where he is constantly looking for ways to speed up websites. He is passionate about web performance and security. Go team web!!

**Duration requested**
15 mins

**Comment by jsstrn** [comment]
Hi @inian, sounds like an interesting talk. See you then.

**Comment by sstrgh** [comment]
**Title** 
PB&J : Protocol Buffers & JSON 

**Talk Description**
I will be talking about a less well known way of serializing data for use in communication protocols and why It might be worth looking at it as compared to JSON/XML 

**Presenter** 
Sunny Singh
https://sg.linkedin.com/in/sunnysatrughan

**Presenter's bio**
Sunny is currently a software developer at Grasshopper Asia Pte Ltd., A high frequency trading firm based in Singapore. Currently he is obsessed with using javascript to building high performance tools for traders.

**Duration Requested**
12 mins

**Comment by jsstrn** [comment]
Hi @satrughan! Looking forward to your talk and learning about protocol buffers.

**Comment by sudheerj** [comment]
**Title:**
Leading open source UI component library for Angular 2

**Talk Description**
I will be talking about what is PrimeNG, Why to choose PrimeNG,how PrimeNG makes Angular 2 applications development rapid and easier with rich set of 80+ UI widgets, and ready made stunning themes to customize look and feel of websites.

**Presenter:**
Sudheer Jonna
https://github.com/sudheerj
https://twitter.com/sudheerjonna

**Presenters Bio**
Sudhee Jonna is a technology enthusiast,author,reviewer,trainer,articles writer,open source contributor (PrimeFaces,PrimeFaces extensions).He is passionate about trending front end and backend technologies.
More details here
https://www.packtpub.com/books/info/authors/sudheer-jonna

**Duration requested:**
15 mins

**Comment by jsstrn** [comment]
Hi @sudheerj! Sorry for the late reply.. looking forward to learning about PrimeNG and it's benefits.

**Comment by ais-one** [comment]
**Title**
NodeJS & Apache Zookeeper

**Talk Description**
Apache ZooKeeper an open-source server which enables highly reliable distributed coordination. I will be focusing on building ZooKeeper aware node.js applications for high availability & horizontal scalability use cases.

**Presenter**
Aaron Gong
https://sg.linkedin.com/in/aaron-gong-a5bb3851

**Presenter's bio**
Information on my work is currently under embargo until after product launch. My hobby is build something to handle 1 million request per second reliably and resiliently, getting there step-by-step.

**Duration Requested**
10mins

**Comment by jsstrn** [comment]
Hi @ais-one, we've maxed out this month's slots for speakers. Would you like to propose this talk in our next meet up? I'll ping you again. Thank you so much and apologies for any inconvenience caused. 

I've created an issue for future proposed talks here https://github.com/SingaporeJS/organizers/issues/40 and added your talk.

**Comment by jsstrn** [comment]
Fully booked for this month. Please submit proposed talks to https://github.com/SingaporeJS/organizers/issues/40
