### ISSUE TITLE
Meetup Venue

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#4]
We usually host talk.js meetup at Microsoft. But for the last few months we also hosted it at AWS and PayPal due to unavailability at Microsoft. Autodesk also offered to to host us, but we didn't go with it because it's at Block 71.

Moving forward, should we continue hosting it at Microsoft or should we rotate between few venues? Personally I like the new PayPal office better. The environment is brighter and I have more connections over there.

**Comment by sayanee** [comment]
I'm fine with rotating venues in the central area. Blk71 is cool too - can reach out to the many startup developers located there.

**Comment by sebdeckers** [comment]
For FEDS TL;DR I intentionally rotate venues, though not limited to any given part of Singapore.

I simply require the host company to have front-end engineering at that office. Maybe host Talk.js meetups at companies that engage in JavaScript development and/or are hiring JavaScript engineers?

**Comment by shawnlimws** [comment]
@caalberts, for the front-end TL:DR  venue, we can populate the list here? Then maybe we can slowly approach them :smile: Or should we create a separate issue for it?
1. Sonoport

**Comment by sebdeckers** [comment]
@shawnlimws This seems somewhat off topic to the original question of this issue. Feel free to create a new issue; they're free. :smile:

**Comment by notthetup** [comment]
For Sonoport contact @hongkheng

**Comment by shawnlimws** [comment]
@notthetup thanks!

**Comment by timoxley** [comment]
This seems resolved for now.
