### ISSUE TITLE
talk.js - talk proposals

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#40]
Hey there! 👋

🗣 Want to speak at talk.js? Great! We'd love to have you over as a speaker. Leave a comment here with the details below and we'll get back to you soon. 

✈️ If you're visiting Singapore for a short period, let us know your preferred dates and we'll see if we can accommodate to your schedule (no promises though).

☕️ You can also reach out to @cheeaun and check out KopiJS https://github.com/KopiJS/kopi.js/issues for a more casual meet up with like-minded people over coffee. 

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: 5min, 10min, 15min
> **Preferred month**: We have one meetup each month
> **Deck URL (if any)**: you can add this part in later

**Comment by jsstrn** [comment]
**Title**
NodeJS & Apache Zookeeper

**Talk Description**
Apache ZooKeeper an open-source server which enables highly reliable distributed coordination. I will be focusing on building ZooKeeper aware node.js applications for high availability & horizontal scalability use cases.

**Presenter**
Aaron Gong @ais-one
https://sg.linkedin.com/in/aaron-gong-a5bb3851

**Presenter's bio**
Information on my work is currently under embargo until after product launch. My hobby is build something to handle 1 million request per second reliably and resiliently, getting there step-by-step.

**Duration Requested**
10mins

**Comment by ais-one** [comment]
I will be busy after CNY till middle of the year, so I guess will have to
do it later, may have more things to cover by then :)

**Comment by abser** [comment]
**Title:** 
Redux store to manage React Native app state and data
**Talk description:** 
React Native, created by Facebook Team, is a popular Javascript framework to develop native iOS and Android application. When we use Redux store with React Native, total development becomes beautiful and it eases effort on state and data management in all screens in an app.
**Presenter:** Md Nurul Abser
**Presenter's bio:** https://www.linkedin.com/in/abser
**Duration requested:** 15min
**Deck URL (if any):** TBD

**Comment by jsstrn** [comment]
Hi @abser, do you have a preferred month when you'd like to present your talk? February may or may not be available (we're trying to get a special guest speaker for February's meetup).

**Comment by abser** [comment]
Hi Jesstern,
I preferred in February if there is a available slot, otherwise in March.

**Comment by sudheerj** [comment]
@jsstrn When will be next meetup plan after this feb. I mean approximate date in march.

**Comment by jsstrn** [comment]
@sudheerj our next talk.js meetup in March is scheduled for 30 March 2017 (Thu). Please keep in mind that this is not yet confirmed.

**Comment by jsstrn** [comment]
Hello speakers, @sudheerj @abser @ais-one, our next meetup is on 30 March, 2017 (Thu). Please add your proposals here https://github.com/SingaporeJS/organizers/issues/42 if you'd like to speak in March. Thank you!

**Comment by jsstrn** [comment]
@sudheerj your talk is scheduled for our meet up in March.

**Comment by ais-one** [comment]
Hi,

March and April is quite busy for me as I have a rollout, I will do it in
May.



*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by abser** [comment]
I am trying to make it. I will confirm soon by next few days.
Abser

**Comment by jsstrn** [comment]
We might be changing the date for our March meet up. Please check #42 for updates.

**Comment by jsstrn** [comment]
We have one more slot open for March meet up https://github.com/SingaporeJS/organizers/issues/42

**Comment by jsstrn** [comment]
Next talk.js will be held on 20 April. Add your talks here https://github.com/SingaporeJS/organizers/issues/44 if you want to speak in April. @abser @ais-one

**Comment by zellwk** [comment]
Title of your talk: Using Fetch. 
Talk description: success and error handling with Fetch + intro my small little Lib :) 
Presenter: @zellwk. 
Presenter's bio: You know me. Write anything you want 😉. 
Duration requested: 10min
Preferred month: May 
Deck URL (if any): none yet.

**Comment by jsstrn** [comment]
Next talk.js is on 20 April, there's still one more slot anyone wants to give a talk. Add your talk to #44

**Comment by sebdeckers** [comment]
Title of your talk: Http2live, a CDN for the HTTP/2 era
Talk description: This talk will focus on a brand new web hosting service that I purpose-built for new features in HTTP/2. Server push with Cache Manifests. Connection coalescing with Alternative Services. Cache control with the immutable extension. Everything is JavaScript/Node.js.
Presenter: Sebastiaan Deckers TW/GH/GL: @sebdeckers
Presenter's bio: I have spent the better part of the past year hacking on HTTP/2 with Node.js, building various tools and contributing to the Node.js core implementation along the way. Life before H2 is but a distant memory.
Duration requested: 15min
Preferred month: 2017-07
Deck URL (if any): TBA

**Comment by tester-me** [comment]
Title of your talk: Build a bot on NodeJS
Talk description: The tools to build a bot quickly, the platforms to build a bot on, what are the possibilities with a bot, testing of the bot, and where to deploy it on etc, the future of bots and how do bots succeed
Presenter: Stacy Goh, github.com/stacygohyunsi
Presenter's bio: Maker/A self taught developer, currently working for an SME to build mobile apps, loves creating side projects, meddling with new technologies and writes for medium regularly. Have 2 years of experience fiddling around with NodeJS. built a bot to find cafes around Singapore called Kopiboy on FB messenger.
Duration requested: 10min
Preferred month: Aug (flexible)
Deck URL (if any): TBA

**Comment by stacygohyunsi** [comment]
Title of your talk: Build a bot on NodeJS
Talk description: The tools to build a bot quickly, the platforms to build a bot on, what are the possibilities with a bot, testing of the bot, and where to deploy it on etc, the future of bots and how do bots succeed
Presenter: Stacy Goh, github.com/stacygohyunsi
Presenter's bio: Maker/A self taught developer, currently working for an SME to build mobile apps, loves creating side projects, meddling with new technologies and writes for medium regularly. Have 2 years of experience fiddling around with NodeJS. built a bot to find cafes around Singapore called Kopiboy on FB messenger.
Duration requested: 10min
Preferred month: Aug (flexible)
Deck URL (if any): TBA

**Comment by jsstrn** [comment]
## 🚛 talk.js has moved to its own repo

Hi speakers, we'll be moving to a different [repo](https://github.com/SingaporeJS/talk.js) to manage the talk.js metup. All future talk proposals should go to the [issues page](https://github.com/SingaporeJS/talk.js/issues). 

@stacygohyunsi I've moved your talk to talk.js August. Looking forward to seeing you then.

Will be closing this issue to avoid confusion.
