### ISSUE TITLE
talk.js - February 2017 (Guest Speaker: Douglas Crockford)

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#41]
### Details
- [x] Event URL on Meetup.com: [talk.js](https://www.meetup.com/Singapore-JS/events/)
- [x] Date: February 16, 2017 - Thursday
- [x] Hosts: @jsstrn
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal

### Speaker
- [x] Douglas Crockford @douglascrockford

**Fully booked for this month.** Please submit proposed talks to https://github.com/SingaporeJS/organizers/issues/40

Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: 5min, 10min, 15min
> **Deck URL (if any)**: you can add this part in later

### Organizers' to-dos
- [x] Create event on SingaporeJS Meetup Page
- [x] Announce on SingaporeJS Gitter, Twitter, Facebook, etc.
- [ ] Submit attendee list to venue host
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by awreccan** [comment]
@jsstrn Is the date still negotiable? If so, PayPal might be able to get Doug Crockford to give a talk. Last I've heard, his dates here are 14-15 Feb.

**Comment by jsstrn** [comment]
@awreccan yes, the date is still flexible.. let me know once you get a confirmation. Thank you for the update.

**Comment by awreccan** [comment]
@douglascrockford is available on 16 Feb for a talk at 7pm! @jsstrn hope this works!

**Comment by jsstrn** [comment]
That's great news, @awreccan! We usually start talks at 7.30pm and allow folks to have pizza from 7pm to 7.30pm. Are we able to start at 7.30pm or is 7pm preferred?

**Comment by awreccan** [comment]
@douglascrockford Does 7:30pm work instead?

**Comment by awreccan** [comment]
@jsstrn Doug is ok with 730

**Comment by jsstrn** [comment]
@awreccan did Douglas mention what his talk will be about? A short write up would be nice so I can put that up on Meetup.com. The last talk he presented on the Seif Project.

**Comment by realsoelynn** [comment]
@jsstrn The title is "Post JavaScript Apocalypse"
