### ISSUE TITLE
talk.js - March 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#42]
### Details
- [x] Event URL on Meetup.com: [talk.js](https://www.meetup.com/Singapore-JS/events/237845979/)
- [x] Date: 16 March, 2017 (Thursday)
- [x] Hosts: @jsstrn
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal

### Talks
- [x] PrimeReact: Leading open source UI component library for React by Sudheer Jonna
- [x] Compiling to JavaScript with Scala.js by Li Haoyi
- [x] Easy React Native using Exponent by Simon Sturmer
- [ ] _You?_

### Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: 5min, 10min, 15min
> **Deck URL (if any)**: you can add this part in later

### Propose a talk next month
Can't speak this month? Add your proposal here instead https://github.com/SingaporeJS/organizers/issues/40

### Organizers' todos
- [x] Create event on SingaporeJS Meetup Page
- [ ] Announce on SingaporeJS Gitter, Twitter, Facebook, etc.
- [ ] Submit attendee list to venue host
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by jsstrn** [comment]
Hi @soelynn, could we book 30 March (Thu) for next month's talk.js? Thanks, mate!

**Comment by realsoelynn** [comment]
yep :)

**Comment by sudheerj** [comment]
Title:
PrimeReact: Leading open source UI component library for React

Talk Description
I will be talking about what is PrimeReact, Why to choose PrimeReact,how PrimeReact makes React applications development rapid and easier with rich set of UI widgets, and ready made stunning themes to customize look and feel of websites.

Presenter:
Sudheer Jonna
https://github.com/sudheerj
https://twitter.com/sudheerjonna

Presenters Bio
Sudhee Jonna is a technology enthusiast,author,speaker,reviewer,trainer,articles writer,open source contributor (PrimeFaces,PrimeFaces extensions).He is passionate about trending front end and backend technologies.
More details here
sudheerjonna.com

Duration requested:
15 mins

**Comment by realsoelynn** [comment]
@jsstrn is it possible to move the date to 31 March?

**Comment by jsstrn** [comment]
We may change the date for our March meet up. Will keep you posted on the changes. Thank you for your understanding.

**Comment by jsstrn** [comment]
The date for March meet up is on 16 March, 2017 (Thursday).

@sudheerj please check your availability and get back to me. Sorry for any inconvenience caused and thank you for your understanding.

**Comment by sudheerj** [comment]
@jsstrn Thanks for informing and it's fine for me.I will update you for any changes.

**Comment by lihaoyi** [comment]
This is the place to submit talk proposals for the march meetup right? 😄 If so here's one:

**Title**
Compiling to Javascript with Scala.js

**Talk Description**
This talk will explore the world of compile-to-JS languages: why would you use a compile-to-JS language? How does it work? What are the downsides? We will explore what it looks like to use a compile-to-JS language in a real-world application, and how it compares to using "raw" Javascript.

**Presenter**
Li Haoyi
https://github.com/lihaoyi
https://twitter.com/li_haoyi

**Presenters Bio**
Haoyi is a software engineer, previously at Dropbox, who is currently working on a developer tools startup. He is interested in programming-languages, developer productivity, and web-development, and the intersection of these: making web-development more productive via improvement to our programming-languages.

**Duration requested**
15min, but I could take up to 30-45min if there's time...

**Comment by jsstrn** [comment]
Thanks @lihaoyi.. looking forward to your talk

**Comment by sstur** [comment]
If you're still open for presenters, I'd be keen to do a short talk on rapidly building React Native apps using [Expo](https://expo.io). This will be an adaptation of a talk I gave in Jakarta on 7th March.

**Title:**
Easy React Native using Expo

**Description:**
This presentation is about rapidly getting up and running using React Native with Expo. Expo provides a set of developer tools built on React Native for a streamlined developer experience including rapid prototyping, iterating and deployment. The goal of this talk is to show you how to get a simple app built and running on a real device within 15min.

**Presenter:**
Simon Sturmer
https://github.com/sstur
[https://twitter.com/sstur_](https://twitter.com/sstur_)

**Presenter's bio:**
Simon is a JavaScript enthusiast who drank the React flavoured Koolaid and enjoys all things React Native. Founder, traveller. Previously at Facebook California. Currently calls Jakarta home. Runs a devteam building mostly React Native.

**Duration requested:** 15min

[EDIT] Updated to reflect the [name change Exponent -> Expo](https://blog.expo.io/exponent-expo-b172fb6725a7).

**Comment by sstur** [comment]
Thanks @jsstrn, for adding my talk to the list! Look forward to meeting you all in Singapore next week.
