### ISSUE TITLE
This issue was created with ghi

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#45]
Using ghi to create and comment on issues so I don't have to do it via a web browser.

**Comment by jsstrn** [comment]
Leaving a comment on ghi

**Comment by sebdeckers** [comment]
Ghi?

**Comment by notthetup** [comment]
https://github.com/stephencelis/ghi

**Comment by sebdeckers** [comment]
![](https://media.giphy.com/media/huh7lUqEG4irK/giphy.gif)
