### ISSUE TITLE
VoxxedDays Singapore - Free ticket for one of the members

### ISSUE THREAD

**Issue by gpotet** [SingaporeJS/organizers#46]
Hi SingaporeJS,

You might have heard that there will be a VoxxedDays happening this year in Singapore, we were wondering if you'd be okay to relay the information to the users of the meetup group. We would like to offer a 10% discount to the SingaporeJS users with the code "SINGAPOREJS-WITH-VOXXED-DAYS"

Also, if you were keen to do some kind of lucky draw amongst the persons present in the next meetup, we would offer one free ticket.

You can check out the program there : [https://voxxeddays.com/singapore/program/](https://voxxeddays.com/singapore/program/)

What do you think?

**Comment by jsstrn** [comment]
Hi @Gpotet, there's open announcements after the scheduled talks where you can make this announcement to the audience. The next meet up is on 20 April #44  

You could ask a question to the audience and the give a free ticket to the one who answers it first. 

You're welcome to do the announcement before the scheduled talks, too, if you prefer.

**Comment by jsstrn** [comment]
@Gpotet thanks for coming and making your announcement. All the best for the conference!
