### ISSUE TITLE
talk.js - May 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#47]
### Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/239896507/)
- [x] Date: 18 May 2017
- [x] Hosts: @jsstrn
- [x] Venue: PayPal Singapore, Suntec Tower 5

### Talks
- [ ] _You?_
- [x] From Instances to Functions: Going Serverless with Node.js by @yosriady 
- [x] Angular and ngrx by @Stwissel 

### Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: 5min, 10min, 15min
> **Deck URL (if any)**: you can add this part in later

### Organizers' todos
- [x] Confirm date and venue space with sponsors
- [x] Inform @engineersftw for video recordings
- [x] Create event on SingaporeJS Meetup Page
- [ ] Announce event on SingaporeJS Gitter, Twitter, Facebook, etc.
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by yosriady** [comment]
**Title of your talk:** From Instances to Functions: Going Serverless with Node.js
**Talk description:** Run your Node.js applications without servers! A serverless architecture approach replaces long-running virtual machines with ephemeral compute power that comes into existence on request and disappears immediately after use. Pay for the hamburger, not the cow!
**Presenter:** http://yos.io https://github.com/yosriady https://www.linkedin.com/in/yosriady/
**Presenter's bio:** Yos works with Node.js and Serverless full-time in production at @bandlab.
**Duration requested:** 30mins
**Deck URL (if any)**: https://goo.gl/hvrw9s

**Comment by Stwissel** [comment]
**Title**: Angular and ngrx
**Description**: Introduction into ngrx, Angular's implementation of a Redux architecture. Comes with lots of Observables and debugging in the browser.
**Presenter**: https://www.wissel.net/
**Presenter's bio**: Stephan likes to talk about stuff he didn't understand before, ex IBM Program Architect at Salesforce
**Duration requested**: 15 min (can make it longer if appropriate)
**Deck URL**: https://stwissel.github.io/presentations/ (after the talk)

I'm traveling, only back after 15 May -> does that fit?

**Comment by laktek** [comment]
**Title of your talk:** Introducing Pragma
**Talk description:** Pragma is a new kind of a Content Management Framework I've been working on for the past couple of months ([intro blog post](www.laktek.com/2016/11/29/introducing-pragma/)). If this talk happens this would be the first time I'm demoing Pragma in public. #historyinmaking
**Presenter:** https://twitter.com/laktek @laktek
**Presenter's bio:** Previously, I worked for Nitrous and Atlassian. I also accidentally started KopiJS
**Duration requested:** 15min

I'd be in Singapore only for a short period (25-30 May) for GopherCon. Can we have the meetup on 29th or 30th?

**Comment by jsstrn** [comment]
@yosriady @Stwissel @laktek hello there! Sorry for the late reply, I'm currently on holiday in Japan. 

Thanks for your talk proposals! Our current meet up is scheduled for 18 May. Does that work for everyone? 

@laktek I'll have to check with @soelynn if we can move to that date, but it's unlikely.

**Comment by yosriady** [comment]
@jsstrn 18th May works for me.

**Comment by jsstrn** [comment]
@yosriady @Stwissel @engineersftw the next talk.js meet up is on 18 May. Here's the [link to the event on Meetup.com](https://www.meetup.com/Singapore-JS/events/239896507/)

**Comment by Stwissel** [comment]
works for me too

**Comment by sudheerj** [comment]
@jsstrn Is it all the speakers slots booked for this meetup?

**Comment by jsstrn** [comment]
Hi @sudheerj! Yup, we'll keep it to two speakers per meet up. You're welcome to submit your talk for next month.

**Comment by sudheerj** [comment]
Sure, I will submit for next month. Do we have link for that. In my humble opinion it is worth to continue 3 speakers so that attendees get the max in 2 hrs time :)
