### ISSUE TITLE
talk.js - June 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#48]
### :calendar: Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/240521034/)
- [x] Date: 20 June 2017 (Tuesday)
- [x] Hosts: @jsstrn
- [x] Venue: PayPal Singapore, Suntec Tower 5

### :speech_balloon: Talks
- [x] Data visualizations on Singapore by **Chi-Loong**
- [x] Using Apollo with ReactJS and GraphQL by **Martin Brochhaus**
- [ ] _You?_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
**Talk description**: tell us what you'd like to talk about
**Presenter**: include GitHub handles where possible
**Presenter's bio**: a short introduction of yourself
**Duration requested**: 5min, 10min, 15min, 30min
**Deck URL (if any)**: you can add this part in later

### :loudspeaker: Open announcement
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Checklist
- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue space with @soelynn 
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [x] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by Chi-Loong** [comment]
**Title of your talk:** Data visualizations on Singapore
**Talk description:** Have you created data visualizations on Singapore (especially if using open data)? Then I would love to talk to you! Meanwhile, let me take you through a quick walkthrough on why data visualizations make such a difference in storytelling. 
**Presenter:** Chi-Loong. I run and curate Visualizing Singapore (http://www.viz.sg/)
**Presenter's bio:** Viz.sg is a non-profit collection of data visualizations on Singapore. It is my belief that these are useful for Singaporeans. In my day job I run a frontend UX dev shop, V/R (www.vslashr.com)
**Duration requested:** 20min
**Deck URL (if any):** http://decks.vslashr.com/journey3D (Am probably going to retweak this for a more technical audience).

I am trying to find people who have written visualizations on Singapore!

**Comment by jsstrn** [comment]
Hi @Chi-Loong :wave: looking forward to having you join us at next month's talk.js and presenting your talk on data visualizations on Singapore.

**Comment by Chi-Loong** [comment]
Hi Jesstern, noted and thanks! 😄

**Comment by jsstrn** [comment]
@soelynn is 20 June 2017 (Tuesday) available?

**Comment by realsoelynn** [comment]
@jsstrn yes. It's available and I have booked it for talkJS :)

**Comment by jsstrn** [comment]
@soelynn thank you!

**Comment by jsstrn** [comment]
@engineersftw @soelynn @Chi-Loong talk.js will be held on 20 June 2017 (Tuesday) at PayPal Singapore. Please RSVP on [Meetup.com](https://www.meetup.com/Singapore-JS/events/240521034/) and share the link on social media.

**Comment by Chi-Loong** [comment]
Hi, Jesstern! Ok! Noted. :D Have a great weekend folks!

**Comment by mbrochh** [comment]
**Title of your talk:** Using Apollo with ReactJS and GraphQL
**Talk description:** GraphQL has been released in 2015 and now it has reached a point where there are very good and stable GraphQL-server implementation for pretty much any language and many database backends. Now would be a great time to upgrade four ReactJS frontend and make use of your new GraphQL API. React-Apollo is a fantastic library that is very easy to integrate into any frontend and allows you to use the power of GraphQL today!
**Presenter:** Martin Brochhaus. I am the CTO of theartling.com and the founder of bitlabstudio.com
**Presenter's bio:** Martin is an open source enthusiast with more than 150 repositories on GitHub and a very active member of the local Python User Group Singapore. He is still specialized on Django-projects for the backend, but with the rise of ReactJS and ReactNative, he spends most of his time writing JavaScript code for the fronend, now.
Duration requested: 20min

**Comment by jsstrn** [comment]
Hi @mbrochh 👋, thanks for submitting your talk.. I've added it to the talk list.

**Comment by mbrochh** [comment]
@jsstrn here are my slides: https://speakerdeck.com/mbrochh/using-apollo-with-reactjs-and-graphql

**Comment by jsstrn** [comment]
Thanks @mbrochh for the talk and like slide deck.
@Chi-Loong would you like to share your slide deck as well?

**Comment by jsstrn** [comment]
@Chi-Loong just saw that you posted on Meetup.com - http://decks.vslashr.com/journey3D/#/start

**Comment by Chi-Loong** [comment]
Hi Jesstern,

  I posted a link up on the SingaporeJs meetup!

  But it' here as well:
http://decks.vslashr.com/journey3D/

Cheers,
CL

**Comment by sebdeckers** [comment]
Closing as the event is over. Thanks for the interesting evening, everyone!
