### ISSUE TITLE
Presentation topics

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#5]
Let's brainstorm here on presentation topics that might be interesting to the audience.
## Topics that are not yet covered

These are topics that are not yet covered but might be interesting to the audience:
- Electron
- Flux
- Flow
- Service Worker
- Fetch API
- WebCrypto
- WebSpeech
- Browser Plugins
- Packaged Apps
- Browser Devtools
- WebAssembly
- Immutable.js
## Interesting topics that have been covered

These are topics that have been covered before. We have speakers who are expert in these topics, and should discuss when should these topics be presented again.
- React
- WebRTC
- WebAudio
- WebGL
- WebComponents
- Emscripten
## Topics that have been covered multiple times

These are topics that are commonly requested to be presented. We'll need to figure if repeating these topics would be interesting to the audience.
- Express and standard web stacks
- Grunt, Gulp, and build tools

Comment here on the topics I might have missed, and I will add them to the lists above.

**Comment by notthetup** [comment]
It's kinda early for WebAssembly no?? I haven't seen much demo-able stuff on their mailing list either.

For Electron, I nominate CheeAun.

What about WebComponents? It has been covered briefly, but we should have a more in-depth look?

I would personally also love to listen to talks about making Chrome/FF plugins/packaged apps.

Seb Deckers had a demo at KopiJS on WebSpeech API. That would be interesting too.

WebCrypto?

**Comment by sayanee** [comment]
Topics not covered are great list @soareschen :heart_eyes: 

Could you include them in your introductory slides at each talk.js? And then ask around who has already played with it - they can give a tiny demo for 5 minutes to 20 minutes.

**Comment by sayanee** [comment]
3 more ways of getting topics / speakers:
- keep a lookout in social media (facebook / twitter) for projects and approach them right away
- approach the creators of [popular local, recently updated javascript repositories](https://webuild.sg/api/v1/repos/javascript)
- spot beginners at nodeschool / nodeboats / peripheral JS related workshops to give a 5 minute sharing session on what happened during the workshop & what they learnt

**Comment by valentine** [comment]
> For Electron, I nominate @cheeaun.

FTFY. :wink: 

How about functional JavaScript? :stuck_out_tongue_closed_eyes: I think @soareschen would be awesome in giving an intro and his thoughts on it. Hehehe.

**Comment by soareschen** [comment]
Great suggestions. Added the suggested topics to the list.

**Comment by soareschen** [comment]
Great suggestions. Added the suggested topics to the list.

**Comment by sayanee** [comment]
i forgot another great way to get speakers - welcome any visiting developers in town and invite them to give a talk or share about their hometown developer community, events, etc. 

We usually try to [re-tweet them with the webuildsg account](https://twitter.com/webuildsg) - so keep a lookout :smile:

**Comment by ongmin** [comment]
For easy editing, topics thread has been moved to Wiki page: [Presentation topics for talk.js](https://github.com/SingaporeJS/organizers/wiki/Presentation-topics-for-talk.js). :)
This issue will be closed soon.
