### ISSUE TITLE
NodeSchool Sept

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#6]
We have been talking about organizing NodeSchool for a long time, but I just didn't make it through. Let's organize a NodeSchool for next month, and one more in November for DevFest.Asia.
- [ ] Date: Saturday 29/8.
- [ ] Venue: IDA@Labs at NDC
- [ ] Food & beverages
- [ ] Pricing (paid or free?)
- [ ] Workshop Materials
- [ ] Mentors

Let us know if you know any other company that can sponsor the venue.

**Comment by notthetup** [comment]
Not sure how the interest would be, but I could mentor the one on WebAudio.

**Comment by sayanee** [comment]
:+1: LGTM - yes, venue is the first step

**Comment by valentine** [comment]
@miccheng, @zgiber and myself brainstormed a whole list of venues on the train home today:

**Central**
- Microsoft
- *SCAPE
- The Hub
- Working Capitol
- The Co
- SMU

**West**
- Singapore Polytechnic
- BASH
- Plug-In@Blk71

The big question is: are we certain that we'll have ~50 attendees? It sounds like a chicken-and-egg type of situation. :confused:

**Comment by timoxley** [comment]
LGTM. 29th works well for me as I won't be back in Singapore until late August.

**Comment by notthetup** [comment]
I haven't been to BASH, but if it can host that number of people, it's pretty convenient (2mins from MRT). Also, the couple of new malls nearby mean there are lunch options. 

PlugIn is good too. It's slightly further, but has 2-3 rooms (not sure if they're still available for use), which could be used for different sessions.

**Comment by soareschen** [comment]
Microsoft said they can host us in weekend. :D

**Comment by valentine** [comment]
🎉✨

**Comment by soareschen** [comment]
Ouch they say cannot after discussion. Still have to look for other venue. I will try to ask Autodesk.

**Comment by soareschen** [comment]
I have booked with IDA@Labs use the NDC 3rd floor for NodeSchool on 29/8. Next up need to plan workshop materials and pricing.

**Comment by soareschen** [comment]
Change of plan. I might need to go back to Malaysia on 29/8. Is it ok to change it to Saturday 5/9?

**Comment by notthetup** [comment]
WeBuildSG doesn't have any events of 5/9.

**Comment by sebdeckers** [comment]
What ever happened to this?

**Comment by soareschen** [comment]
I let it slipped through and stopped following up on the venue, so have to cancel and just do the November one with DevFest. :(
