### ISSUE TITLE
DevFest.Asia

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#7]
@serrynaimo have shared with us details about organizing events under [DevFest.Asia](http://2015.devfest.asia/) between 7th - 21st of November.

Quoting [what is provided](https://jsconfasia.wufoo.com/forms/devfestasia-2015-list-my-event/) by DevFest.Asia to event organizers:
- Up to S$2500 to help your event budget from our sponsors
- Unified ticketing and ticket support handling
- You get 100% of the ticket income for everyone attending your event
- Your event will be listed on our DevFest.Asia website and get exposure through our online and offline advertising efforts
- We help you get an awesome venue in the Singapore CBD if you need one
- You get access to our supplier catalog for food, drinks and event equipment

I think we can organize at least two events within that period, with few more possible workshops:
- Talk.js
- NodeSchool
- WebAudio + WebGL School
- [Tessel](https://tessel.io/) workshop

With the S$2500 sponsorship we can probably think of more interesting events to organize as well.

**Comment by serrynaimo** [comment]
Cool :) Just remember it's "up to 2500". The better you can outline what you'll use it for the easier it is for us to assign it.

**Comment by soareschen** [comment]
Let's plan out the timing for DevFest first:
- talk.js - Tuesday 10/11
- NodeSchool - Saturday 14/11
- WebAudio Hack Day - Sunday 15/11

How does that sound?

**Comment by serrynaimo** [comment]
FYI: We currently plan an important meetup about "working in sg" on the 14th in the afternoon.

**Comment by soareschen** [comment]
Ah alright. Then perhaps:
- talk.js - Tuesday 10/11
- NodeSchool - Sunday 15/11
- WebAudio Hack Day - Satrday 21

**Comment by sebdeckers** [comment]
- FEDS TL;DR - Monday 16/11

**Comment by notthetup** [comment]
:+1: I will submit the proposal for WebAudio Hack Day today.

**Comment by notthetup** [comment]
Submitted.

![screenshot 2015-07-29 09 41 28](https://cloud.githubusercontent.com/assets/553140/8948116/07516d9c-35d6-11e5-98fe-4c81571f6d1c.jpg)

**Comment by serrynaimo** [comment]
Sweet :) Will respond during early August when I have a more complete overview.

**Comment by sebdeckers** [comment]
> - The registered organizer will be responsible for the well being of the event and will be enforcing our code-of-conduct

Anyone know what that entails? @serrynaimo Where can I find this code of conduct?

**Comment by serrynaimo** [comment]
http://jsconf.com/codeofconduct.html

**Comment by sebdeckers** [comment]
Interesting.

> Sponsors are also subject to the anti-harassment policy. In particular, sponsors should not use sexualized images, activities, or other material. Booth staff (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment.

I didn't know we were in [Malaysia](http://news.bbc.co.uk/1/hi/entertainment/8315829.stm)...

> Conference staff can be identified by a clearly marked "STAFF" shirt.

Even at meetups or only for JSConf/CSSConf?

> Conference staff will be happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the conference. We value your attendance.

What does "provide escorts" entail? I think "to feel safe" is totally subjective and could be used to justify anything. What is "your attendance" doing in this paragraph?

**Comment by serrynaimo** [comment]
The code of conduct is deliberatly broad. We want to avoid that any person coming to the devfest.asia events needs to feel insecure and that they behave in a respectful manner towards others. We have this coc since JSCamp in 2012 and point attendees, speakers and aponsors towards it. It is meant as a guide and point of reference for devfest event organizers to point to exclude instigators and trouble-makers from events. Which hopefully will not be required in the first place ;)

**Comment by soareschen** [comment]
Submitted mine as well.

![screenshot from 2015-07-29 23 41 55](https://cloud.githubusercontent.com/assets/97665/8962116/7318d8d8-364b-11e5-9155-45a9f7ad3061.png)
![screenshot from 2015-07-29 23 41 38](https://cloud.githubusercontent.com/assets/97665/8962118/7504bca2-364b-11e5-8281-10699dd47030.png)
